### ISSUE TITLE
Four pre-existing mypy no-any-return/return-value errors in scripts/validation modules

### ISSUE THREAD

**Issue by rjmurillo** [rjmurillo/ai-agents#2880]
## Summary

While fixing #2876 (pre-push mypy false positives on `checks_*` wrappers), enabling `MYPYPATH=scripts/validation` surfaced four PRE-EXISTING type errors in unrelated `scripts/validation` modules. These are NOT introduced by #2876: the error count is identical with and without MYPYPATH, and none of these files use the bare intra-package import pattern.

The current pre-push gate already flags each of these when the file itself changes (it runs `mypy <changed-file>` per file). They are latent only because the files have not been edited. Filing so a future edit does not surprise-block, and so they can be fixed as a batch.

## Inventory (ground-truthed with `mypy`, repo config)

| File:line | Error |
|---|---|
| `scripts/validation/check_dual_priority_labels.py:128` | `Incompatible return value type (got "tuple[int, list[Any \| None], str]", expected "tuple[int, list[str] \| None, str]")` [return-value] |
| `scripts/validation/memory_index.py:532` | `Incompatible types in assignment (expression has type "Match[str] \| None", variable has type "Match[str]")` [assignment] |
| `scripts/validation/validate_agent_catalog.py:54` | `Returning Any from function declared to return "int"` [no-any-return] |
| `scripts/validation/validate_hook_anchoring.py:123` | `Returning Any from function declared to return Module` [no-any-return] |

## Reproduction

```bash
for f in check_dual_priority_labels memory_index validate_agent_catalog validate_hook_anchoring; do
  mypy scripts/validation/$f.py
done
```

Each reports exactly one error with OR without `MYPYPATH=scripts/validation` set.

## Suggested fixes (each ~1 line)

- `check_dual_priority_labels.py:128` - annotate the intermediate list as `list[str] | None` or cast the tuple element.
- `memory_index.py:532` - keep the `Match[str] | None` type (guard the None) instead of asserting `Match[str]`.
- `validate_agent_catalog.py:54` - cast the returned value to `int` (likely a `re`/`dict` lookup returning `Any`).
- `validate_hook_anchoring.py:123` - annotate/cast the returned module.

## Priority

P3. No runtime bug (types only); pre-existing; blocks only on direct edit of each file. Deliberately kept out of #2876 to keep that fix surgical.

## Provenance

Diagnosed during #2876 fix (PR #2879). Verified pre-existing via with/without MYPYPATH comparison and confirmed none use bare imports.

**Comment by rjmurillo** [comment]
## Velocity Accelerator: 2 Opportunities Detected

### Triage issue #2880: Four pre-existing mypy no-any-return/return-value errors in 
- **Type**: complexity_triage
- **Priority**: medium
- **Suggested Agent**: agent-architect
- Issue labeled with low complexity.
Suggested agents: agent-architect

### Route issue #2880 to agent-architect
- **Type**: agent_routing
- **Priority**: low
- **Suggested Agent**: agent-architect
- Issue content suggests routing to: agent-architect
Complexity: low
