### PR TITLE
fix(validation): resolve 4 pre-existing mypy type errors (#2880)

### LINKED ISSUE #2880: Four pre-existing mypy no-any-return/return-value errors in scripts/validation modules
## Summary

While fixing #2876 (pre-push mypy false positives on `checks_*` wrappers), enabling `MYPYPATH=scripts/validation` surfaced four PRE-EXISTING type errors in unrelated `scripts/validation` modules. These are NOT introduced by #2876: the error count is identical with and without MYPYPATH, and none of these files use the bare intra-package import pattern.

The current pre-push gate already flags each of these when the file itself changes (it runs `mypy <changed-file>` per file). They are latent only because the files have not been edited. Filing so a future edit does not surprise-block, and so they can be fixed as a batch.

## Inventory (ground-truthed with `mypy`, repo config)

| File:line | Error |
|---|---|
| `scripts/validation/check_dual_priority_labels.py:128` | `Incompatible return value type (got "tuple[int, list[Any \| None], str]", expected "tuple[int, list[str] \| None, str]")` [return-value] |
| `scripts/validation/memory_index.py:532` | `Incompatible types in assignment (expression has type "Match[str] \| None", variable has type "Match[str]")` [assignment] |
| `scripts/validation/validate_agent_catalog.py:54` | `Returning Any from function declared to return "int"` [no-any-return] |
| `scripts/validation/validate_hook_anchoring.py:123` | `Returning Any from function declared to return Module` [no-any-return] |

## Reproduction

```bash
for f in check_dual_priority_labels memory_index validate_agent_catalog validate_hook_anchoring; do
  mypy scripts/validation/$f.py
done
```

Each reports exactly one error with OR without `MYPYPATH=scripts/validation` set.

## Suggested fixes (each ~1 line)

- `check_dual_priority_labels.py:128` - annotate the intermediate list as `list[str] | None` or cast the tuple element.
- `memory_index.py:532` - keep the `Match[str] | None` type (guard the None) instead of asserting `Match[str]`.
- `validate_agent_catalog.py:54` - cast the returned value to `int` (likely a `re`/`dict` lookup returning `Any`).
- `validate_hook_anchoring.py:123` - annotate/cast the returned module.

## Priority

P3. No runtime bug (types only); pre-existing; blocks only on direct edit of each file. Deliberately kept out of #2876 to keep that fix surgical.

## Provenance

Diagnosed during #2876 fix (PR #2879). Verified pre-existing via with/without MYPYPATH comparison and confirmed none use bare imports.

### PR DESCRIPTION
**Pull request by rjmurillo**
## Summary

Resolves the 4 pre-existing mypy errors tracked in #2880. These are orthogonal to the #2876 hook change that first surfaced them under the per-file `MYPYPATH` pass. All fixes are behavior-preserving.

## Changes

- `scripts/validation/check_dual_priority_labels.py`: use `str(item["name"])` so the comprehension yields `list[str]` instead of `list[Any | None]`. The items are already filtered on a truthy `name`, so indexing is safe and `str()` is a no-op on the existing string.
- `scripts/validation/memory_index.py`: rename the inner `search()` result to `parsed_link` so it no longer shadows the `finditer()` loop variable (`Match[str]`) with a `Match[str] | None`.
- `scripts/validation/validate_agent_catalog.py`: wrap the delegated call in `int(...)` because the dynamically imported catalog generator is untyped and returns `Any`.
- `scripts/validation/validate_hook_anchoring.py`: `cast(ModuleType, generate_hooks)` for the untyped dynamic import.

## Evidence

> [!NOTE]
> Verified with `mypy` under `MYPYPATH` (the same per-file pass added for #2876): all four files report `Success: no issues found`. The four module test suites pass (115 tests). `ruff check` reports no issues. `run_plugin_version_bump_ci.py` returns OK (validation scripts are not plugin source, so no manifest bump is required).

## Out of Scope

> [!NOTE]
> The hook wiring that made these visible shipped separately in the #2876 PR. This PR only corrects the four flagged type errors.

Closes #2880

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>

### CODE REVIEW

File: scripts/validation/validate_agent_catalog.py [hunk 1]
```diff
@@ -51,8 +51,10 @@ def main(argv: Sequence[str] | None = None) -> int:
         print(f"Error: cannot import build/generate_agent_catalog.py: {exc}", file=sys.stderr)
         return 2
 
-    return generate_agent_catalog.main(
-        ["--check", "--templates-path", str(templates_dir), "--output", str(output_path)]
+    return int(
+        generate_agent_catalog.main(
+            ["--check", "--templates-path", str(templates_dir), "--output", str(output_path)]
+        )
     )
```
[the remark this answers is not in the document]
Comment (rjmurillo) [reply scripts/validation/validate_agent_catalog.py]: Fixed in deef17f36. You are both correct that `int(...)` is a runtime coercion rather than behavior-preserving. `generate_agent_catalog.main` is annotated `-> int` and every return path yields an int, so the original mypy error was `[no-any-return]` (the dynamic `import generate_agent_catalog` makes the call return `Any` under `warn_return_any = true`), a typing concern, not a runtime one. Switched to `cast(int, ...)`, which is a no-op at runtime and satisfies mypy, consistent with the `cast(ModuleType, ...)` approach already used in `validate_hook_anchoring.py`. Verified: mypy clean, ruff clean, runtime `main([])` returns int 0.

[the remark this answers is not in the document]
Comment (rjmurillo) [reply scripts/validation/validate_agent_catalog.py]: Fixed in deef17f36. You are both correct that `int(...)` is a runtime coercion rather than behavior-preserving. `generate_agent_catalog.main` is annotated `-> int` and every return path yields an int, so the original mypy error was `[no-any-return]` (the dynamic `import generate_agent_catalog` makes the call return `Any` under `warn_return_any = true`), a typing concern, not a runtime one. Switched to `cast(int, ...)`, which is a no-op at runtime and satisfies mypy, consistent with the `cast(ModuleType, ...)` approach already used in `validate_hook_anchoring.py`. Verified: mypy clean, ruff clean, runtime `main([])` returns int 0.
