### PR TITLE
fix(ratchet): remove the dead type-ignore that turned main red

### PR DESCRIPTION
**Pull request by rjmurillo**
## Problem

`origin/main` is red. Any open PR that still carries the 56th occurrence inherits the failure:

```
type-ignore count ratchet: REGRESSION. 56 violations > baseline 55 (+1)
```

Reproduced on a pristine checkout of `origin/main` with zero local changes, and observed on the CI of two unrelated PRs whose diffs contain no Python at all.

## Cause

An ordering race between two independently green PRs.

| When | PR | Effect on the count |
|------|----|---------------------|
| 2026-07-31 11:46 UTC | #4093 (`cea600edc8`) | Added the ratchet and its baseline of 55. Correct at the time: the count at that commit is exactly 55. |
| 2026-07-31 18:04 UTC | #4091 (`088292977f`) | Added one suppression, taking the count to 56. No baseline bump. |

Neither PR saw the other. Both were green on their own branch. Main went red only once both had landed. This is the same failure shape as a stale version bump: a baseline computed against `origin/main` at PR creation time goes stale when a sibling lands first.

Verified by counting at each commit:

```
git grep -o -E '#\s*type:\s*ignore' cea600edc8 -- '*.py' | wc -l   # 55
git grep -o -E '#\s*type:\s*ignore' origin/main  -- '*.py' | wc -l   # 56
```

and by diffing the per-file tallies between the two commits, which isolates exactly one added occurrence.

## Fix

Delete the added suppression in `scripts/validation/pr_commit_count.py`. It is provably dead:

```
$ uv run mypy --warn-unused-ignores scripts/validation/pr_commit_count.py
scripts/validation/pr_commit_count.py:238: error: Unused "type: ignore" comment  [unused-ignore]
```

mypy infers the surrounding value as `Any`, so there is no `arg-type` error for the comment to suppress. Removing it is behavior preserving. The explanatory comment on the line above is kept, because it still documents the invariant the helper enforces for human readers.

The baseline stays at 55 rather than rising to 56. Raising it would permanently widen the ceiling to admit a suppression that mypy says is unnecessary.

## Verification

```
type-ignore count ratchet: OK (count == baseline 55)          exit 0
tests/validation/test_pr_commit_count.py                      98 passed
tests/ci/test_type_ignore_count_ratchet.py                    17 passed
mypy + ruff on the changed file                               clean
```

Negative control: stashing this single line restores `exit 1` with the same message, and restoring it returns `exit 0`. The change is what fixes the gate, not anything environmental.

## Impact: main is currently failing this gate

The ratchet is a whole repo count compared against a baseline file that is
checked in beside it. Both inputs live on main, and main's own tree does not
satisfy its own baseline.

Direct measurement on a clean detached checkout of `origin/main` at 088292977f:

```text
$ uv run python scripts/ci/type_ignore_count_ratchet.py
type-ignore count ratchet: REGRESSION. 56 violations > baseline 55 (+1).
exit 1
```

The same command on this branch:

```text
type-ignore count ratchet: OK (count == baseline 55).
exit 0
```

The two trees differ by exactly the one line this PR deletes. Confirmed by
diffing every Python file and the baseline file between them: empty.

Two open PRs inherit the failure without introducing it. #4136 changes sixteen
markdown and JSON files and zero Python files, and is red on this check. #4131
is red for the same reason. Four other open PRs are green because their trees
either predate the suppression or already delete it.

That makes this a repair of a broken default branch rather than a cleanup, so
it wants to merge ahead of the queue.

## Notes

One further unused suppression exists and is deliberately left alone, to keep this PR to the single line that unblocks the repository:

```
scripts/github_core/bot_config.py:13: error: Unused "type: ignore" comment  [unused-ignore]
```

It predates the baseline, so it is already inside the 55 and is not causing the failure. `warn_unused_ignores` is not enabled repo-wide, which is why both survived. Enabling it would catch this class at authoring time and is worth its own PR.

### Overlap with an open PR

Adversarial review surfaced that #4124 independently carries the identical one-line deletion, bundled into a larger change to the rule-activation eval instrument. Verified with `gh pr diff 4124`.

Either PR unblocks the ratchet, so this one is not required. It is kept separate because it is reviewable in one line and #4124 carries unrelated scope. Whichever merges first makes the other's hunk a no-op; the loser resolves a one-line conflict. Close this PR instead if the preference is to let #4124 carry it.

### A separate defect found during review, deliberately not fixed here

`_external_non_first_parent_shas` reads `parent.get("sha")` twice: once inside `_is_external_parent` for validation, once at the call site for insertion. A `dict` subclass whose `get` returns different values on successive calls can insert a SHA that was never validated. Reproduced locally.

It is unreachable from the production path, because the payload arrives through `json.loads`, which emits plain `dict` and never a subclass. It also predates this diff. Fixing it means changing the helper's signature and adding a regression test, which would take this PR past the single line that unblocks the repository, so it ships separately.

Refs #4039

### CODE REVIEW

**Comment by rjmurillo** [comment]
Closing as superseded by current `origin/main` and the sibling duplicate #4139.

Measured:
- #4138 and #4139 both target the same #4091 dead `type: ignore[arg-type]` in `scripts/validation/pr_commit_count.py`.
- #4138 also adds broader hardening and tests around hostile mapping values. That is outside the ratchet fix described by the PR.
- Current `origin/main` no longer has the suppression. It uses `shas.add(parent["sha"])` after `_is_external_parent` narrows the value.
- `uv run --frozen python scripts/ci/type_ignore_count_ratchet.py --base-ref origin/main` on `origin/main` passes with `count == baseline 53`.

No branch change remains required for this PR's stated fix.
